# Generated by Django 5.2.4 on 2025-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_quiz_num_of_qus_alter_quiz_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
