# Generated by Django 5.2.4 on 2025-08-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_quizattempt_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_options',
            new_name='selected_option',
        ),
    ]
