# Generated by Django 5.2.4 on 2025-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[('one', 'Option1'), ('two', 'Option2'), ('three', 'Option3'), ('four', 'Option4')]),
        ),
    ]
