# Generated by Django 5.2.4 on 2025-08-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(),
        ),
    ]
