# Generated by Django 5.2.4 on 2025-08-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quizattempt_end_time_alter_answer_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='end_time',
        ),
    ]
