# Generated by Django 5.2.4 on 2025-08-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_quizattempt_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='review_on',
            field=models.BooleanField(default=False),
        ),
    ]
