# Generated by Django 5.2.4 on 2025-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_quizattempt_review_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='review_on',
        ),
        migrations.AddField(
            model_name='quiz',
            name='review_on',
            field=models.BooleanField(default=False),
        ),
    ]
